project_id = "miaifxqtqpuxogpgjwty"

[functions.get-google-maps-key]
verify_jwt = true

[functions.check-in]
verify_jwt = true

[functions.checkout]
verify_jwt = true

[functions.expire-checkins]
verify_jwt = false

[functions.get-nearby-locations]
verify_jwt = true

[functions.get-users-at-location]
verify_jwt = true

[functions.process-like]
verify_jwt = true

[functions.process-unlike]
verify_jwt = true

[functions.send-notification]
verify_jwt = false
